# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 01:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='date',
        ),
        migrations.AddField(
            model_name='successstory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 7, 1, 41, 8, 156384, tzinfo=utc), verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successstory',
            name='description',
            field=models.CharField(default='Success Story description', max_length=255),
        ),
        migrations.AddField(
            model_name='successstory',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='author',
            field=models.CharField(default='Author', max_length=50),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='content',
            field=models.TextField(default='Story content'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='title',
            field=models.CharField(default='Story Title', max_length=100),
        ),
    ]
