# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160406_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='text',
            field=models.CharField(default='test', max_length=25),
        ),
    ]
