# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_successstory_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='text',
        ),
        migrations.AddField(
            model_name='successstory',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
