# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160411_1550'),
    ]
