# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_successstory_published'),
        ('blog', '0005_auto_20160409_1515'),
    ]

    operations = [
    ]
