# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_successstory_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='successstory',
            name='article_picture',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
