# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160428_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='article_picture',
            field=models.ImageField(blank=True, upload_to=b'education_haiti/static/img_blog/', verbose_name=b'img'),
        ),
    ]
