# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160429_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='article_picture',
            field=models.ImageField(blank=True, upload_to=b'media/', verbose_name=b'img'),
        ),
    ]
