# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160517_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['-created']},
        ),
    ]
