# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_successstory_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='top_story',
            field=models.BooleanField(default=False),
        ),
    ]
