# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 19:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rank', models.CharField(choices=[(b'A', b'mentor'), (b'B', b'mentee')], default=(b'B', b'mentee'), max_length=255, null=True)),
                ('undergrad_college', models.CharField(choices=[(b'1', b'Illinois State University'), (b'2', b'Mount Holyoke College'), (b'3', b'University of Notre Dame'), (b'4', b'Columbia University'), (b'5', b'Cornell University'), (b'6', b'Ecole Polytechnique de Montreal'), (b'7', b'Georgia Tech University'), (b'8', b'Harvard University'), (b'9', b'Louisiana State University'), (b'10', b'Massachusettes Institute of Technology'), (b'11', b'McGill University'), (b'12', b'Moncton University'), (b'13', b'Southern University'), (b'14', b'Tufts University'), (b'15', b'University of Michigan'), (b'16', b'University of Pennsyvalnia'), (b'17', b'Cooper Union'), (b'18', b'St Leo University'), (b'19', b'Stony Brook University'), (b'20', b'University of Ottawa'), (b'21', b'Berea College'), (b'22', b'Massasoit CC'), (b'23', b'University of Massachusetts'), (b'24', b'University of South Florida')], default=b'No University', max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=b'profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=b'profile_images')),
                ('biography', models.TextField()),
                ('undergrad_college', models.CharField(choices=[(b'1', b'Illinois State University'), (b'2', b'Mount Holyoke College'), (b'3', b'University of Notre Dame'), (b'4', b'Columbia University'), (b'5', b'Cornell University'), (b'6', b'Ecole Polytechnique de Montreal'), (b'7', b'Georgia Tech University'), (b'8', b'Harvard University'), (b'9', b'Louisiana State University'), (b'10', b'Massachusettes Institute of Technology'), (b'11', b'McGill University'), (b'12', b'Moncton University'), (b'13', b'Southern University'), (b'14', b'Tufts University'), (b'15', b'University of Michigan'), (b'16', b'University of Pennsyvalnia'), (b'17', b'Cooper Union'), (b'18', b'St Leo University'), (b'19', b'Stony Brook University'), (b'20', b'University of Ottawa'), (b'21', b'Berea College'), (b'22', b'Massasoit CC'), (b'23', b'University of Massachusetts'), (b'24', b'University of South Florida')], default=b'No University', max_length=255)),
                ('grad_college', models.CharField(choices=[(b'1', b'Illinois State University'), (b'2', b'Mount Holyoke College'), (b'3', b'University of Notre Dame'), (b'4', b'Columbia University'), (b'5', b'Cornell University'), (b'6', b'Ecole Polytechnique de Montreal'), (b'7', b'Georgia Tech University'), (b'8', b'Harvard University'), (b'9', b'Louisiana State University'), (b'10', b'Massachusettes Institute of Technology'), (b'11', b'McGill University'), (b'12', b'Moncton University'), (b'13', b'Southern University'), (b'14', b'Tufts University'), (b'15', b'University of Michigan'), (b'16', b'University of Pennsyvalnia'), (b'17', b'Cooper Union'), (b'18', b'St Leo University'), (b'19', b'Stony Brook University'), (b'20', b'University of Ottawa'), (b'21', b'Berea College'), (b'22', b'Massasoit CC'), (b'23', b'University of Massachusetts'), (b'24', b'University of South Florida')], default=b'No University', max_length=255)),
                ('majors', models.CharField(default=b'Your major(s), please separate each major with a comma', max_length=100)),
                ('hidden', models.BooleanField(default=False)),
                ('mentees', models.ManyToManyField(to='people.Mentee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
