# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='interests',
            field=models.CharField(default=b'Your interests, please separate each one with a comma', max_length=150),
        ),
    ]
