# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_mentor_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='residency',
            field=models.CharField(default=b'Your state/city of residency', max_length=255),
        ),
    ]
