# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_mentor_residency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(default=b'Your phone number', max_length=255),
        ),
    ]
