# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_mentor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='current_status',
            field=models.CharField(default=b'Your current status/work', max_length=255),
        ),
        migrations.AddField(
            model_name='mentor',
            name='school_haiti',
            field=models.CharField(default=b'Your school in Haiti', max_length=255),
        ),
    ]
