# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('A', 'mentor'), ('B', 'mentee')], default=('B', 'mentee'), max_length=10),
        ),
    ]
