# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20160611_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='first_name',
            field=models.CharField(default=b'Your first name', max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='last_name',
            field=models.CharField(default=b'Your last name', max_length=100),
        ),
    ]
