# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20160611_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b'mentor_profile_images'),
        ),
    ]
