# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20160611_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentees',
            field=models.ManyToManyField(null=True, to='people.Mentee'),
        ),
    ]
