# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20160717_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=b'New Author', max_length=25)),
                ('subject', models.CharField(default=b'New ToDo', help_text=b'What is this ToDo about', max_length=200)),
                ('emitted', models.DateField(auto_now_add=True)),
                ('expires', models.DateField(help_text=b'Should be enterd in the YYYY-MM-DD format. Ex: 2016-10-28')),
                ('completion', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mentor',
            name='current_status',
            field=models.CharField(default=b'work work work work work', help_text=b'Your current status/work', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='first_name',
            field=models.CharField(help_text=b'Your first name', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='grad_college',
            field=models.CharField(choices=[(b'1', b'Illinois State University'), (b'2', b'Mount Holyoke College'), (b'3', b'University of Notre Dame'), (b'4', b'Columbia University'), (b'5', b'Cornell University'), (b'6', b'Ecole Polytechnique de Montreal'), (b'7', b'Georgia Tech University'), (b'8', b'Harvard University'), (b'9', b'Louisiana State University'), (b'10', b'Massachusettes Institute of Technology'), (b'11', b'McGill University'), (b'12', b'Moncton University'), (b'13', b'Southern University'), (b'14', b'Tufts University'), (b'15', b'University of Michigan'), (b'16', b'University of Pennsyvalnia'), (b'17', b'Cooper Union'), (b'18', b'St Leo University'), (b'19', b'Stony Brook University'), (b'20', b'University of Ottawa'), (b'21', b'Berea College'), (b'22', b'Massasoit CC'), (b'23', b'University of Massachusetts'), (b'24', b'University of South Florida'), (b'25', b'Princeton University'), (b'26', b'Montclair State University'), (b'27', b'University of Georgia'), (b'28', b'------------------------')], default=b'No University', help_text=b'Your Graduate College', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='interests',
            field=models.CharField(help_text=b'Your interests, please separate each one with a comma', max_length=150),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='last_name',
            field=models.CharField(help_text=b'Your last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='majors',
            field=models.CharField(help_text=b'Your major(s), please separate each major with a comma', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(default=b'+(000)0000000', help_text=b'Your phone number', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='residency',
            field=models.CharField(help_text=b'Your state/city of residency', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='school_haiti',
            field=models.CharField(default=b'Institution Alea Touare', help_text=b'Your school in Haiti', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='undergrad_college',
            field=models.CharField(choices=[(b'1', b'Illinois State University'), (b'2', b'Mount Holyoke College'), (b'3', b'University of Notre Dame'), (b'4', b'Columbia University'), (b'5', b'Cornell University'), (b'6', b'Ecole Polytechnique de Montreal'), (b'7', b'Georgia Tech University'), (b'8', b'Harvard University'), (b'9', b'Louisiana State University'), (b'10', b'Massachusettes Institute of Technology'), (b'11', b'McGill University'), (b'12', b'Moncton University'), (b'13', b'Southern University'), (b'14', b'Tufts University'), (b'15', b'University of Michigan'), (b'16', b'University of Pennsyvalnia'), (b'17', b'Cooper Union'), (b'18', b'St Leo University'), (b'19', b'Stony Brook University'), (b'20', b'University of Ottawa'), (b'21', b'Berea College'), (b'22', b'Massasoit CC'), (b'23', b'University of Massachusetts'), (b'24', b'University of South Florida'), (b'25', b'Princeton University'), (b'26', b'Montclair State University'), (b'27', b'University of Georgia'), (b'28', b'------------------------')], default=b'No University', help_text=b'Your Undergraduate College', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='undergrad_college',
            field=models.CharField(choices=[(b'1', b'Illinois State University'), (b'2', b'Mount Holyoke College'), (b'3', b'University of Notre Dame'), (b'4', b'Columbia University'), (b'5', b'Cornell University'), (b'6', b'Ecole Polytechnique de Montreal'), (b'7', b'Georgia Tech University'), (b'8', b'Harvard University'), (b'9', b'Louisiana State University'), (b'10', b'Massachusettes Institute of Technology'), (b'11', b'McGill University'), (b'12', b'Moncton University'), (b'13', b'Southern University'), (b'14', b'Tufts University'), (b'15', b'University of Michigan'), (b'16', b'University of Pennsyvalnia'), (b'17', b'Cooper Union'), (b'18', b'St Leo University'), (b'19', b'Stony Brook University'), (b'20', b'University of Ottawa'), (b'21', b'Berea College'), (b'22', b'Massasoit CC'), (b'23', b'University of Massachusetts'), (b'24', b'University of South Florida'), (b'25', b'Princeton University'), (b'26', b'Montclair State University'), (b'27', b'University of Georgia'), (b'28', b'------------------------')], default=b'No University', max_length=255),
        ),
    ]
