# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20160722_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='current_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='interests',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='majors',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(default=b'+(000)0000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='residency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='school_haiti',
            field=models.CharField(max_length=255),
        ),
    ]
