# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20160728_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[(b'A', b'Mentor'), (b'B', b'Admin')], default=(b'B', b'Admin'), max_length=255, null=True),
        ),
    ]
