# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20160729_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='grad_college',
            field=models.CharField(choices=[('1', 'Illinois State University'), ('2', 'Mount Holyoke College'), ('3', 'University of Notre Dame'), ('4', 'Columbia University'), ('5', 'Cornell University'), ('6', 'Ecole Polytechnique de Montreal'), ('7', 'Georgia Tech University'), ('8', 'Harvard University'), ('9', 'Louisiana State University'), ('10', 'Massachusettes Institute of Technology'), ('11', 'McGill University'), ('12', 'Moncton University'), ('13', 'Southern University'), ('14', 'Tufts University'), ('15', 'University of Michigan'), ('16', 'University of Pennsyvalnia'), ('17', 'Cooper Union'), ('18', 'St Leo University'), ('19', 'Stony Brook University'), ('20', 'University of Ottawa'), ('21', 'Berea College'), ('22', 'Massasoit CC'), ('23', 'University of Massachusetts'), ('24', 'University of South Florida'), ('25', 'Princeton University'), ('26', 'Montclair State University'), ('27', 'University of Georgia'), ('28', 'Slippery Rock University'), ('29', 'University of Rochester'), ('30', 'TRCC'), ('31', 'Syracuse University'), ('32', 'University of Virginia'), ('33', "St John's University"), ('34', 'Wake Forest University'), ('35', 'N/A')], default='No University', help_text='Your Graduate College', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(default='+(000)0000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='picture',
            field=models.ImageField(blank=True, upload_to='mentor_profile_images'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='undergrad_college',
            field=models.CharField(choices=[('1', 'Illinois State University'), ('2', 'Mount Holyoke College'), ('3', 'University of Notre Dame'), ('4', 'Columbia University'), ('5', 'Cornell University'), ('6', 'Ecole Polytechnique de Montreal'), ('7', 'Georgia Tech University'), ('8', 'Harvard University'), ('9', 'Louisiana State University'), ('10', 'Massachusettes Institute of Technology'), ('11', 'McGill University'), ('12', 'Moncton University'), ('13', 'Southern University'), ('14', 'Tufts University'), ('15', 'University of Michigan'), ('16', 'University of Pennsyvalnia'), ('17', 'Cooper Union'), ('18', 'St Leo University'), ('19', 'Stony Brook University'), ('20', 'University of Ottawa'), ('21', 'Berea College'), ('22', 'Massasoit CC'), ('23', 'University of Massachusetts'), ('24', 'University of South Florida'), ('25', 'Princeton University'), ('26', 'Montclair State University'), ('27', 'University of Georgia'), ('28', 'Slippery Rock University'), ('29', 'University of Rochester'), ('30', 'TRCC'), ('31', 'Syracuse University'), ('32', 'University of Virginia'), ('33', "St John's University"), ('34', 'Wake Forest University'), ('35', 'N/A')], default='No University', help_text='Your Undergraduate College', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.CharField(default='New Author', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('A', 'Mentor'), ('B', 'Admin')], default=('B', 'Admin'), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='undergrad_college',
            field=models.CharField(choices=[('1', 'Illinois State University'), ('2', 'Mount Holyoke College'), ('3', 'University of Notre Dame'), ('4', 'Columbia University'), ('5', 'Cornell University'), ('6', 'Ecole Polytechnique de Montreal'), ('7', 'Georgia Tech University'), ('8', 'Harvard University'), ('9', 'Louisiana State University'), ('10', 'Massachusettes Institute of Technology'), ('11', 'McGill University'), ('12', 'Moncton University'), ('13', 'Southern University'), ('14', 'Tufts University'), ('15', 'University of Michigan'), ('16', 'University of Pennsyvalnia'), ('17', 'Cooper Union'), ('18', 'St Leo University'), ('19', 'Stony Brook University'), ('20', 'University of Ottawa'), ('21', 'Berea College'), ('22', 'Massasoit CC'), ('23', 'University of Massachusetts'), ('24', 'University of South Florida'), ('25', 'Princeton University'), ('26', 'Montclair State University'), ('27', 'University of Georgia'), ('28', 'Slippery Rock University'), ('29', 'University of Rochester'), ('30', 'TRCC'), ('31', 'Syracuse University'), ('32', 'University of Virginia'), ('33', "St John's University"), ('34', 'Wake Forest University'), ('35', 'N/A')], default='No University', max_length=255),
        ),
    ]
