# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20170717_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
