# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_remove_mentor_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='highlighy',
            field=models.BooleanField(default=False),
        ),
    ]
