# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_mentor_highlighy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='highlighy',
            new_name='highlight',
        ),
    ]
