# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(help_text=b'Where the Program will take place/will be offered', max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('slug', models.SlugField()),
                ('details', models.TextField(help_text=b'Other details concerning the Program', max_length=300)),
                ('fee', models.IntegerField(help_text=b'All fees in Haitian Gourdes HTG', null=True)),
                ('phone_contact', models.CharField(help_text=b'Phone number', max_length=255)),
                ('email_contact', models.EmailField(max_length=254)),
                ('deadline', models.DateField(help_text=b'Deadline to get in')),
                ('expired_deadline', models.BooleanField(default=False, help_text=b'did the deadline pass?')),
                ('expired_final', models.BooleanField(default=False, help_text=b'Did the Program end?')),
                ('picture', models.ImageField(blank=True, upload_to=b'program_picures/', verbose_name=b'img')),
            ],
        ),
    ]
