# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 30, 0, 38, 42, 560769, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programs',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 30, 0, 38, 52, 585147, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
