# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20160729_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='deadline',
            field=models.DateField(help_text='Deadline to get in'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='details',
            field=models.TextField(help_text='Other details concerning the Program', max_length=300),
        ),
        migrations.AlterField(
            model_name='programs',
            name='expired_deadline',
            field=models.BooleanField(default=False, help_text='did the deadline pass?'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='expired_final',
            field=models.BooleanField(default=False, help_text='Did the Program end?'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='fee',
            field=models.IntegerField(help_text='All fees in Haitian Gourdes HTG', null=True),
        ),
        migrations.AlterField(
            model_name='programs',
            name='location',
            field=models.CharField(help_text='Where the Program will take place/will be offered', max_length=255),
        ),
        migrations.AlterField(
            model_name='programs',
            name='phone_contact',
            field=models.CharField(help_text='Phone number', max_length=255),
        ),
        migrations.AlterField(
            model_name='programs',
            name='picture',
            field=models.ImageField(blank=True, upload_to='program_picures/', verbose_name='img'),
        ),
    ]
